### ISSUE TITLE
Header: Responsive error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Novacare#126]
![image](https://cloud.githubusercontent.com/assets/12888048/15002058/af3f42c4-11cf-11e6-96d6-49ce0b55a8de.png)

**Comment by romatitan** [comment]
Align the logo properly inside in area.
![image](https://cloud.githubusercontent.com/assets/12888048/15134803/1790eec8-16a2-11e6-981e-d3695c9c5850.png)

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/15345918/adbc754a-1ce5-11e6-8a66-3aad13f79523.png)

**Comment by kabirkhan123** [comment]
To make the banner responsive,  background of header should be relative otherwise banner wont be responsive.
