### ISSUE TITLE
Homepage - Gallery: Incorrect size of the image

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Novacare#138]
![image](https://cloud.githubusercontent.com/assets/12888048/15003073/68f5855c-11da-11e6-8dc1-4e57abc18f46.png)

**Comment by romatitan** [comment]
There should have a total of 6 images display in the gallery, then slides the rest of the image.

**Comment by kabirkhan123** [comment]
Given psd's width is 2100px, so the width will be same(350x372) in that port.
