### ISSUE TITLE
Real Estate: It seems the sort/filter property details are hard coded

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Novacare#149]
1. Create ACF for Suburb. Suburb drop-down list should display all SUBURB values
2. Price Low / Price High drop-down list should display all the price from PRICE ACF
3. Car drop-down list should display all CAR values
4. Bath drop-down list should display all BATH values
5. Bed drop-down list should display all BED values

![image](https://cloud.githubusercontent.com/assets/12888048/15006380/d9af9d8c-1202-11e6-9aaa-39ed85c36085.png)

**Comment by kabirkhan123** [comment]
as you said acf field are already created. here is the screenshot.Please provide the clarity on this issue.
![titan theme options novacare wordpress 2016-05-18 12-04-08](https://cloud.githubusercontent.com/assets/16079664/15391508/1b100c66-1ddf-11e6-8f8c-4254eee4b13a.png)
