### ISSUE TITLE
Real Estate Listing: Pixelated default no image

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Novacare#163]
![image](https://cloud.githubusercontent.com/assets/12888048/15138380/faf76f1a-16c1-11e6-8fc1-4836b5ee789b.png)

**Comment by kabirkhan123** [comment]
The logo in the psd is of low resolution , provide high resolution logo.

**Comment by henrytitan** [comment]
The distortion of the image is cause by the logo.

**Comment by romatitan** [comment]
Client provided a low resolution logo.
