### ISSUE TITLE
Header: There's a background color on the site logo

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Novacare#32]
![image](https://cloud.githubusercontent.com/assets/12888048/14555863/a11cae0e-0327-11e6-89c2-b6ac933b2be5.png)

**Comment by kabirkhan123** [comment]
Implemented according to the design.

**Comment by romatitan** [comment]
This is not invalid. **Pending issue.**
Calvin already requested a better version of the logo from the client.
