### ISSUE TITLE
Lead-ins: "Lead-ins Per Row on Mobile" field is not working

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Novacare#57]
![image](https://cloud.githubusercontent.com/assets/12888048/14595245/6b83f98c-0570-11e6-8fb7-2b361e5649e3.png)

**Comment by kabirkhan123** [comment]
Leadins were stretched, if we implement 2 per row(see the below screenshot
![leadin](https://cloud.githubusercontent.com/assets/16079664/14841871/a1103ec6-0c5f-11e6-9d71-36fe3d6035b8.png)
). so implemented single row in mobile view.

**Comment by romatitan** [comment]
Does it mean that the user can't control the number of lead-ins to be displayed per row on mobile?
What the use of this "Leadins Per Row on mobile" ACF?
![image](https://cloud.githubusercontent.com/assets/12888048/14950461/5bc4802e-1084-11e6-9106-11ae5a7bf5ec.png)

**Comment by kabirkhan123** [comment]
This Acf fiels are not in use so we should remove these Acf fields
