### ISSUE TITLE
Lead-ins per Row on Tablet errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Novacare#58]
**3 lead-ins in a Row** : Lead-ins were stretched vertically
**2 lead-ins in a Row** : Overlapping elements (lead-ins and intro section). 
The 3rd lead-ins should be in the center.
**1 lead-ins in a Row** : Overlapping elements (lead-ins and intro section). 
Below the banner aligned the lead-ins in the center. 

![image](https://cloud.githubusercontent.com/assets/12888048/14595424/a4c87924-0571-11e6-899f-6e7363f66865.png)

**Comment by romatitan** [comment]
**iPad portrait view **: Lead-ins did not display on 3 per row
![image](https://cloud.githubusercontent.com/assets/12888048/14950551/18c59226-1085-11e6-8e2b-83665c0760a5.png)

**Comment by kabirkhan123** [comment]
This Acf fiedls are not in use so we should remove these Acf fields
