### ISSUE TITLE
General: Incorrect font-family, size and color for UL and OL content

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Novacare#73]
**Homepage** should have the ff,
font-family: Arial
font-size: 18px
color: #fff

**Gallery** should have the ff,
font-family: Arial
font-size: 16px
color: #656058

**Comment by kabirkhan123** [comment]
Implemented as per the design.

**Comment by romatitan** [comment]
Here the following style in the given design.
font-family: Arial
font-size: 16px
color: #656058

Kindly apply in Homepage and Gallery.
Please note that the homepage has a dark background so the font should be white.

**Homepage** should have the ff,
font-family: Arial
font-size: 18px
color: #fff

**Gallery** should have the ff,
font-family: Arial
font-size: 16px
color: #656058
